# Generated by Django 6.0.6 on 2026-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique business identifier for the item.', max_length=50, unique=True, verbose_name='item code')),
                ('name', models.CharField(max_length=255, verbose_name='name 1')),
                ('secondary_name', models.CharField(blank=True, max_length=255, verbose_name='name 2')),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('behaviour', models.CharField(blank=True, help_text='Business behaviour classification; allowed values are pending confirmation.', max_length=50)),
                ('group_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-taxable')], default='taxable', max_length=20, verbose_name='taxable status')),
                ('shelf_code', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('code',),
            },
        ),
    ]
