# Generated by Django 6.0.6 on 2026-06-21 08:13

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Unit name or code, for example Pcs or Box.', max_length=50, verbose_name='unit')),
                ('co_factor', models.DecimalField(decimal_places=6, help_text='Number of stock units represented by one of this unit.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='conversion factor')),
                ('barcode', models.CharField(blank=True, help_text='Optional unique barcode for this item unit.', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='Item to which this unit configuration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='items.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'item unit',
                'verbose_name_plural': 'item units',
                'ordering': ('item_id', 'unit'),
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list_type', models.CharField(help_text='Pricing category, for example Retail or Wholesale.', max_length=50, verbose_name='price list type')),
                ('sale_price', models.DecimalField(decimal_places=4, help_text='Default selling price for this item unit.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='sale price')),
                ('minimum_selling_price', models.DecimalField(decimal_places=4, help_text='Lowest permitted selling price for this item unit.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='minimum selling price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_unit', models.ForeignKey(help_text='Configured item unit to which this price applies.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='items.itemunit', verbose_name='item unit')),
            ],
            options={
                'verbose_name': 'item price',
                'verbose_name_plural': 'item prices',
                'ordering': ('item_unit_id', 'price_list_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('unit'), models.F('item'), name='unique_case_insensitive_unit_per_item'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.CheckConstraint(condition=models.Q(('co_factor__gt', 0)), name='item_unit_co_factor_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('price_list_type'), models.F('item_unit'), name='unique_item_unit_price_list_type'),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='item_price_sale_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_selling_price__gte', 0)), name='item_price_min_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_selling_price__lte', models.F('sale_price'))), name='item_price_min_lte_sale'),
        ),
    ]
