# Generated by Django 6.0.6 on 2026-06-21 12:18

from django.db import migrations, models


def normalize_behaviour_values(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    database = schema_editor.connection.alias
    value_map = {
        '': 'stock',
        'stock': 'stock',
        'stock item': 'stock',
        'purchase': 'purchase',
        'purchase item': 'purchase',
        'non stock': 'non_stock',
        'non stock item': 'non_stock',
        'service': 'service',
        'assembly': 'assembly',
    }

    for item in Item.objects.using(database).only('id', 'behaviour').iterator():
        normalized_key = (
            (item.behaviour or '')
            .strip()
            .casefold()
            .replace('-', ' ')
            .replace('_', ' ')
        )
        normalized_value = value_map.get(normalized_key)
        if normalized_value is None:
            raise ValueError(
                f'Cannot migrate unknown Item behaviour value: {item.behaviour!r}'
            )

        if item.behaviour != normalized_value:
            Item.objects.using(database).filter(pk=item.pk).update(
                behaviour=normalized_value
            )


def restore_legacy_behaviour_values(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    database = schema_editor.connection.alias
    value_map = {
        'stock': 'Stock Item',
        'purchase': 'Purchase Item',
        'non_stock': 'Non Stock Item',
        'service': 'Service',
        'assembly': 'Assembly',
    }

    for stored_value, legacy_value in value_map.items():
        Item.objects.using(database).filter(behaviour=stored_value).update(
            behaviour=legacy_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemunit_itemprice_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_behaviour_values,
            restore_legacy_behaviour_values,
        ),
        migrations.AlterField(
            model_name='item',
            name='behaviour',
            field=models.CharField(choices=[('stock', 'Stock Item'), ('purchase', 'Purchase Item'), ('non_stock', 'Non Stock Item'), ('service', 'Service'), ('assembly', 'Assembly')], default='stock', help_text='Defines how the ERP handles the item.', max_length=20),
        ),
    ]
