# Generated by Django 6.0.6 on 2026-06-23 06:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_alter_item_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(help_text='Unique business document number for the quotation.', max_length=50, unique=True, verbose_name='quotation number')),
                ('quotation_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Business date on which the quotation was issued.')),
                ('customer_code', models.CharField(db_index=True, help_text='Customer code captured when the quotation was created.', max_length=50)),
                ('customer_name', models.CharField(help_text='Customer name snapshot retained for historical accuracy.', max_length=255)),
                ('customer_ref_no', models.CharField(blank=True, max_length=100, verbose_name='customer reference number')),
                ('sales_executive', models.CharField(blank=True, max_length=255)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('pay_terms', models.CharField(blank=True, max_length=255, verbose_name='payment terms')),
                ('delivery_place', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('BHD', 'Bahraini Dinar'), ('OMR', 'Omani Rial')], default='SAR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Multiplier used to convert the document currency to base currency.', max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT amount')),
                ('net_after_vat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='net after VAT')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer selected for this quotation.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='sales.customer')),
            ],
            options={
                'verbose_name': 'sales quotation',
                'verbose_name_plural': 'sales quotations',
                'ordering': ('-quotation_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(verbose_name='line number')),
                ('item_code', models.CharField(help_text='Item code snapshot captured when the quotation was created.', max_length=50)),
                ('item_name', models.CharField(help_text='Item name snapshot captured when the quotation was created.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(help_text='Unit snapshot selected for this quotation line.', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='VAT percentage')),
                ('vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='VAT amount')),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='net after VAT')),
                ('item_unit', models.ForeignKey(help_text='Current item-unit reference retained for validation, reporting, and navigation.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_lines', to='items.itemunit')),
                ('quotation', models.ForeignKey(help_text='Quotation header to which this line belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesquotation')),
            ],
            options={
                'verbose_name': 'sales quotation line',
                'verbose_name_plural': 'sales quotation lines',
                'ordering': ('quotation_id', 'line_no'),
            },
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['status', 'quotation_date'], name='sq_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='sq_exchange_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='sq_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sq_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('gross_amount'))), name='sq_discount_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='sq_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='sq_vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('net_after_vat__gte', models.F('net_amount'))), name='sq_total_gte_net'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'line_no'), name='unique_sq_line_number'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gt', 0)), name='sq_line_number_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sq_line_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='sq_line_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='sq_line_discount_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sq_line_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_percentage__gte', 0), ('vat_percentage__lte', 100)), name='sq_line_vat_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='sq_line_vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='sq_line_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('net_after_vat__gte', models.F('net_amount'))), name='sq_line_total_gte_net'),
        ),
    ]
