# Generated by Django 6.0.6 on 2026-06-24 10:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_behaviour'),
        ('sales', '0002_seed_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(max_length=50, unique=True)),
                ('sales_order_type', models.CharField(choices=[('normal', 'Normal')], default='normal', max_length=20)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_po', models.CharField(blank=True, max_length=100, verbose_name='customer PO')),
                ('sales_executive', models.CharField(blank=True, max_length=255)),
                ('delivery_place', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('BHD', 'Bahraini Dinar'), ('OMR', 'Omani Rial')], default='SAR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.salesquotation')),
            ],
            options={
                'ordering': ('-issue_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=4, max_digits=18)),
                ('item_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='items.itemunit')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'ordering': ('sales_order_id', 'line_no'),
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'issue_date'], name='so_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='so_exchange_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('valid_date__isnull', True), ('valid_date__gte', models.F('issue_date')), _connector='OR'), name='so_valid_date_gte_issue'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='so_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='so_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('gross_amount'))), name='so_discount_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='so_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='so_vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('net_after_vat__gte', models.F('net_amount'))), name='so_total_gte_net'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('sales_order', 'line_no'), name='unique_so_line_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gt', 0)), name='so_line_number_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='so_line_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='so_line_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='so_line_discount_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='so_line_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_percentage__gte', 0), ('vat_percentage__lte', 100)), name='so_line_vat_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='so_line_vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='so_line_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('net_after_vat__gte', models.F('net_amount'))), name='so_line_total_gte_net'),
        ),
    ]
