# Generated by Django 6.0.6 on 2026-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_salesorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, help_text='Header image shown at the top of quotation and sales order PDFs.', null=True, upload_to='print-templates/')),
                ('footer_image', models.ImageField(blank=True, help_text='Footer image shown at the bottom of quotation and sales order PDFs.', null=True, upload_to='print-templates/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'print template setting',
                'verbose_name_plural': 'print template settings',
            },
        ),
    ]
