# Generated by Django 6.0.6 on 2026-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_printtemplatesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplatesetting',
            name='primary_color',
            field=models.CharField(default='#312e81', help_text='Primary hex color used for PDF highlights and totals.', max_length=7),
        ),
    ]
